Ncl 6290 expose metrics from kafka store
project-ncl/kafka-store pull request #88
Opened 2021-01-08 15:45 UTC by lbossis

@avibelli

2021-01-08 16:53 UTC, vibe13 requested changes
@lbossis Hi Leo, I might have put you on the wrong path. From the docs, it looks like the micrometer way is recommended for Quarkus-based applications (and it looks easier!). Would you please switch to Micrometer spec please? Thanks!

2021-01-08 16:53 UTC, vibe13 commented on src/main/java/org/jboss/pnc/kafkastore/common/SortedSetOrder.java
> +    @Timed
Mmmm this is not an exposed REST enpdoint, so not sure whether @Timed is applicable. Also, not part of micrometer spec.

2021-01-08 16:53 UTC, vibe13 commented on src/main/java/org/jboss/pnc/kafkastore/rest/MainRest.java
> +@Timed
From https://quarkus.io/guides/micrometer#writing-the-application, it looks like ```Timer``` and `Counter` are automatically exposed for all the endpoints, no need to specify them.
Also, please verify in https://quarkus.io/guides/micrometer#configuration-reference if the defaults are enough for us, or we need to add some configurations.

2021-01-08 16:53 UTC, vibe13 commented on src/main/java/org/jboss/pnc/kafkastore/mapper/BuildStageRecordMapper.java
> +    @Produces(MediaType.TEXT_PLAIN)
I think it's good to track errors. But this is not an endpoint, it's a mapper. You need to move these endpoints to the MainRest class.

2021-01-08 16:53 UTC, vibe13 commented on pom.xml
> +        <dependency>
I am reading from https://quarkus.io/guides/micrometer that Micrometer is the recommended approach to metrics for Quarkus. Could you please switch the implementation to use micrometer instead? You should probably only add these 2 dependencies:
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-micrometer</artifactId>
</dependency>
<dependency>
    <groupId>io.micrometer</groupId>
    <artifactId>micrometer-registry-prometheus</artifactId>
</dependency>
```

2021-01-08 16:53 UTC, vibe13 commented on src/main/java/org/jboss/pnc/kafkastore/facade/BuildMetricsFetcher.java
> +@Timed
Same as above

2021-01-08 16:53 UTC, vibe13 commented on src/main/java/org/jboss/pnc/kafkastore/mapper/BuildStageRecordMapper.java
> +    static final Counter exceptionsTotal = Counter.build()
You can probably use a Gauge (2 Gauges) for these counters, according to examples in https://quarkus.io/guides/micrometer

2021-02-04 14:34 UTC, lbossis commented
Implementation was switched from microprofile to micrometer. This PR will be closed without merge.

2021-02-04 14:34 UTC, closed without merging